// <auto-generated />
namespace AjourBT.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1));
        
        string IMigrationMetadata.Id
        {
            get { return "201310020854131_1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
