// <auto-generated />
namespace AjourBT.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AccComment_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AccComment_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201401131018491_AccComment_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
