// <auto-generated />
namespace AjourBT.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CalendarItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CalendarItem));
        
        string IMigrationMetadata.Id
        {
            get { return "201312311057089_CalendarItem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
