// <auto-generated />
namespace AjourBT.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class holidayMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(holidayMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201312311051274_holidayMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
