// <auto-generated />
namespace AjourBT.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AccComment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AccComment));
        
        string IMigrationMetadata.Id
        {
            get { return "201401131031355_AccComment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
