// <auto-generated />
namespace AjourBT.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Holidays_CheckBox : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Holidays_CheckBox));
        
        string IMigrationMetadata.Id
        {
            get { return "201404180947323_Holidays_CheckBox"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
